name: Full Stack CI Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: npm install

      - name: Run Backend Test
        run: npm test

      - name: Build Backend Docker Image
        run: docker build -t ci-cd-backend .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Docker Image
        run: |
          docker tag ci-cd-backend sirisenagandla/ci-cd-backend:latest
          docker push sirisenagandla/ci-cd-backend:latest  

  frontend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Build Frontend Docker Image
        run: docker build -t ci-cd-frontend .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Frontend Docker Image
        run: |
          docker tag ci-cd-frontend sirisenagandla/ci-cd-frontend:latest
          docker push sirisenagandla/ci-cd-frontend:latest  